services:
  postgresql:
    image: 'crpi-3xjthxff00w1y58m.cn-qingdao.personal.cr.aliyuncs.com/lftec/postgresql:latest'
    restart: always
    container_name: postgresql
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    volumes:
      - /var/postgres:/bitnami/postgresql
    ports:
      - "5432:5432"
    networks:
      - nds-network
  nds:
    image: "crpi-3xjthxff00w1y58m.cn-qingdao.personal.cr.aliyuncs.com/lftec/nds:latest"
    restart: always
    container_name: nds
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - AUTH_URL=${AUTH_URL}
      - AUTH_SECRET=${AUTH_SECRET}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - nds-network

networks:
  nds-network:
    driver: bridge
